### ISSUE TITLE
Hyperlink is not created 

### ISSUE THREAD

**Issue by Skippersquareroot100** [Skippersquareroot100/Laravel-project--1#1]
<img width="569" alt="Screenshot 2024-05-30 at 6 19 41 PM" src="https://github.com/Skippersquareroot100/pro/assets/111722365/d377b717-0b5a-4348-a5a0-115180f921f8">
<img width="569" alt="Screenshot 2024-05-30 at 6 19 25 PM" src="https://github.com/Skippersquareroot100/pro/assets/111722365/2036d0e7-c9fe-4a79-bd93-72b11d82acce">

its linked with: about.blade.php, contact.blade.php, web.php files

**Comment by mehedi8gb** [comment]
Can you make a PR, then assigned me as a reviewer. 
And make a comment on the specific code where you're having problem.

**Comment by mehedi8gb** [comment]
Thanks for addressing the issue, I appreciate your contribution. Let me know if you encounter any other problems or need further assistance. 
Keep up the good work!
